kind: Service
apiVersion: v1
metadata:
  name: {{ include "github-webhook.name" . }}
spec:
  selector:
    {{- include "github-webhook.selectorLabels" . | nindent 6 }}
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8081