name: github-workflow

on:
  push:
    branches:
      - main

jobs:
  github-workflow:
    name: github-workflow
    runs-on: ubuntu-latest
    env:
      TRIM_SHA: ${GITHUB_SHA::8}
    steps:
    - uses: nelonoel/branch-name@v1.0.1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        platforms: linux/arm64
        tags: ${{ steps.login-ecr.outputs.registry }}/github-webhook:latest  #${{ github.workflow }}:latest

    - name: Package and deploy Helm Chart
      uses: wahyd4/kubectl-helm-action@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG }}
      with:
        args: |
          ls
          cd ./helm/github-webhook
          helm package --version ${TRIM_SHA} .
          helm install github-webhook-${TRIM_SHA}.tgz \
          -n restock \
          --set instance=${BRANCH_NAME} \
          --set GITHUB_AUTH_TOKEN=${{ secrets.WEBHOOK_AUTH_TOKEN }}
          github-webhook-${TRIM_SHA}.tgz  