name: github-workflow

on:
  push:
    branches:
      - main

jobs:
  github-workflow:
    name: github-workflow
    runs-on: ubuntu-latest
    steps:

    - name: Test
      run: echo ${{ secrets.AWS_ACCESS_KEY_ID }} ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIASQIVI6MGOWMVVX4A #${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: 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 #${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/arm64
        #push: true
        tags: ${{ steps.login-ecr.outputs.registry }}/${GITHUB_WORKFLOW}:latest

    - name: Deploy helm chart to kubernetes
      uses: 'deliverybot/helm@v1'
      with:
        helm: 'helm3'
        release: ${GITHUB_WORKFLOW}
        namespace: 'restock'
        chart: 'helm/${GITHUB_WORKFLOW}/Chart.yaml'
        chart_version: '1.0.0'
        version: ${GITHUB_SHA::8}
        values: |
          instance: ${GITHUB_REF##*/}
          GITHUB_AUTH_TOKEN: ${{ secrets.WEBHOOK_AUTH_TOKEN }}
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'