name: github-workflow

on:
  push:
    branches:
      - main

jobs:
  github-workflow:
    name: github-workflow
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ECR
        id: ecr
        uses: elgohr/ecr-login-action@master
        with:
          access_key: ${{ secrets.AWS_ACCESS_KEY }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.AWS_REGION }}
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm64
          #push: true
          tags: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-west-1.amazonaws.com/${GITHUB_WORKFLOW}:latest

      - name: Deploy helm chart to kubernetes
        uses: 'deliverybot/helm@v1'
        with:
          helm: 'helm3'
          release: ${GITHUB_WORKFLOW}
          namespace: 'restock'
          chart: 'helm/${GITHUB_WORKFLOW}/Chart.yaml'
          chart_version: '1.0.0'
          version: ${GITHUB_SHA::8}
          values: |
            instance: ${GITHUB_REF##*/}
            GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_AUTH_TOKEN }}
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'